### ISSUE TITLE
Error in "Substitute()" when using piecewise function

### ISSUE THREAD

**Issue by willigott** [sbmlteam/SBMLToolbox#1]
I am using a matlab toolbox that relies on the SBMLToolbox version 4.1 downloaded from [here](https://sourceforge.net/projects/sbml/files/SBMLToolbox/).

I get an error, unfortunately, when I try to load the attached file using the following commands:

```
SBMLModel = TranslateSBML('dummy_model_piecewise.xml', 1, 0);

[ParameterNames, ParameterValues] = GetAllParametersUnique(SBMLModel);
```

Then it crashes with:

>  run piecewise_issue
> The model contains 0 errors and 25 warnings.
> 
> Error using Substitute (line 148)
> Substitute(): Ill formed formula
> 
> Error in GetGlobalParameters (line 101)
>         Values(i) = Substitute(AR.formula, newSBMLModel);
> 
> Error in GetAllParametersUnique (line 63)
> [ParamChar, ParamValues] = GetGlobalParameters(SBMLModel);
> 
> Error in piecewise_issue (line 3)
> [ParameterNames, ParameterValues] = GetAllParametersUnique(SBMLModel);

I guess that is due to the `piecewise` part as it works fine when I remove it and replace it by a constant.

How could this be fixed? Is it due to the version of the SBMLToolbox (if so, which one should be used instead?) or is there another issue?

Thanks!

[piecewise_issue.zip](https://github.com/sbmlteam/SBMLToolbox/files/2205962/piecewise_issue.zip)

**Comment by skeating** [comment]
Thanks for the report.

If you replace the src/Convenience/piecewise.m file in your installation of SBMLToolbox with the version attached 
[piecewise.zip](https://github.com/sbmlteam/SBMLToolbox/files/2213428/piecewise.zip)
this should fix your issue.

**Comment by willigott** [comment]
Thank you very much for this immediate fix, highly appreciated! It indeed loads fine now without any complaints and I therefore close the issue.
