### ISSUE TITLE
What does the function GetAllParametersUnique actually do?

### ISSUE THREAD

**Issue by willigott** [sbmlteam/SBMLToolbox#2]
The title is a bit weird but I did not find a better one... :)

I use a toolbox that relies on the SBMLToolbox. When I read small models, the parsing is very fast, however, when I read a model with 52 parameters and 12 rules, the call

`[ParameterNames, ParameterValues] = GetAllParametersUnique(SBMLModel);`

takes hours (not sure about the exact time as I interrupted the process); `SBMLModel` was loaded using `TranslateSBML`. The reason is not clear to me yet, but it seems that the rule formulas are revisited several times which then sums up for a lot of parameters and rules.

When I looked at the actual code, I was wondering whether I could actually replace the entire function by:

```
function varargout = GetAllParametersUnique(SBMLModel)

% check input is an SBML model
if (~isValidSBML_Model(SBMLModel))
    error('GetAllParametersUnique(SBMLModel)\n%s', 'input must be an SBMLModel structure');
end;

varargout{1} = {SBMLModel.parameter.id};
varargout{2} = [SBMLModel.parameter.value];
```

and so far I have not run into a case where this would not give the exact same output as the original function; this function is, however, far faster, so also the model in question loads quite fast then.  
So, I basically just use the already parsed information about IDs and values directly from the `SBMLModel` structure provided by `TranslateSBML`.

Is there any risk using the function from above i.e. a model structure that would then be parsed incorrectly?

**Comment by skeating** [comment]
Hi

If the model specifies the value for each parameter and it is consistent with a value that is assigned by an initialAssignment or assignmentRule then yes your code will give you exactly the same answers.

However, it is valid in sbml to have a parameter that does not state its initial value but uses another construct to calculate it. It is also valid for a parameter to state an initial value and for that value to be reassigned by another construct.

For example consider a model 

with parameter id="p1" value="2"

and rule that assigns to "p1" which calculates the value to be '4'.

GetAllParametersUnique would then return to you: ["p1"] [4]

but your code would return ["p1"][2] - which would not be the correct initial value for the parameter.

The code in GetAllParametersUnique does not calculate values unless it needs to - so it looks like in the model you were using many of the parameters are assigned by a rule and so the code needs to do the calculations; which can be time intensive.

Hope this clarifies the situation.

Sarah

**Comment by willigott** [comment]
Thanks again for the immediate and detailed reply!

Just to clarify, as I am not a SBML expert:  
I usually use Tellurium/Antimony for the construction of the models.

If I try something like this:

```
import tellurium as te

r = te.loada("""
    model dummy()    

    # Model Definition
    v1: $Xo -> S1;  p1 * Xo;
    v2: S1 -> S2;   k2 * S1;
    v3: S2 -> $X1;  k3 * S2 * en;

    en := gap - S1;
    p1 := 3 - Xo;

    # Initialize constants
    p1 = 2.0;
    k2 = 1.0;
    k3 = 3.0;
    gap = 3.0;
    
    Xo = 2;
    S1 = 3.0;
    S2 = 0.0;    
    
    KM = 0.5;
    n = 2.0;

    end
""")
```

it will fail with

> Exception: Antimony: Error in model string, line 13:  Cannot set 'p1' to have the initial value '2' because it already has an assignment rule, which applies at all times, including time=0.

If I remove ` p1 = 2.0;`, and export the model, then I get (I removed the irrelevant parameters):

```
    <listOfParameters>
      <parameter id="p1" value="1" constant="false"/>
      
    </listOfParameters>
    <listOfRules>
      <assignmentRule variable="p1">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <minus/>
            <cn type="integer"> 3 </cn>
            <ci> Xo </ci>
          </apply>
        </math>
      </assignmentRule>
```

So, both cases behave as I would expect.

If I now understand correctly, `GetAllParametersUnique` protects from the case, where I go to the SBML file and manually change

` <parameter id="p1" value="1" constant="false"/>`

to e.g.

` <parameter id="p1" value="10" constant="false"/>`

Using your code, the correct value  `1` would be returned, while my version would return the incorrect value `10`.

Do I understand this correctly? Is there any other way to get contradicting values for a parameter in the `values` field and the one calculated in a rule besides the manual physical replacement in the file? As I always create the files using  Antinomy, I should be on the safe side, I think, but I would like to avoid the introduction of inconsistencies by accident.

Thanks! 

In my actual file, I indeed have a lot of rules, some of which are even nested. I will check whether I can simplify this.

**Comment by skeating** [comment]
Hi 

Yes your assessment is correct. My code would recalculate the correct initial value of p1 where yours would assume it was correct.

From the sbml file point of view, an assignment rule or an initialAssignment may overwrite the value of a parameter placed in the 'value' attribute on the parameter element.  People writing tools can add code that checks for inconsistency - as Antimony clearly does. If you only create models using Antimony - you could check with the Antimony developers or documentation to see whether there are any situations where it would export the inconsistency. If Antimony only exports consistent models then changing the code in GetAllParametersUnique would be fine for your use. You would need to careful if you are creating a tool that you will share with others as you would be removing the check that SBMLToolbox does for the inconsistent situation.

Sarah

**Comment by willigott** [comment]
Hi Sarah,

Thanks once again for the detailed reply and clarification!

I will leave the function `GetAllParametersUnique` untouched but will replace its call in the toolbox I am using by the two lines required to retrieve IDs and values (as I only work with models created with Antimony this should be fine...).
